### ISSUE TITLE
Stop method on receiver is causing session error to be emitted

### ISSUE THREAD

**Issue by Bruce-at-Buddy** [Azure/azure-event-hubs-node#115] opened 2018-07-25 04:09 UTC
**Describe the bug**

Session error being fired when receiver's stop method is called

```
> node src/receiveSimple.js

Client created
receiveHandler Stopping

events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: The link handle '0' cannot be found in session 'session5078199'.
    at Session.on_end (Projects/event-hub-test/node_modules/rhea/lib/session.js:637:86)
    at Connection.(anonymous function) [as on_end] (Projects/event-hub-test/node_modules/rhea/lib/connection.js:680:30)
    at c.dispatch (Projects/event-hub-test/node_modules/rhea/lib/types.js:909:33)
    at Transport.read (Projects/event-hub-test/node_modules/rhea/lib/transport.js:108:36)
    at SaslClient.read (Projects/event-hub-test/node_modules/rhea/lib/sasl.js:277:26)
    at Connection.input (Projects/event-hub-test/node_modules/rhea/lib/connection.js:438:35)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
```

**To Reproduce**

```js
const { EventHubClient, EventPosition } = require('azure-event-hubs');

async function main() {

    const { EVENTHUB_CONNECTION_STRING, EVENTHUB_NAME } = process.env;
    const client = await EventHubClient.createFromConnectionString(
        EVENTHUB_CONNECTION_STRING, EVENTHUB_NAME
    );

    console.info('Client created');

    const onError = (err) => {
        console.fatal("An error occurred on the receiver ", err.message);
        console.fatal(err);
        process.exit(127);
    };

    let timeout = null;
    const onMessage = (eventData) => {
        if (timeout === null) {
            timeout = setTimeout(async () => {
                console.info('receiveHandler Stopping');
                await receiveHandler.stop();

                console.info('receiveHandler Stopped');

                await client.close();
                console.info('Stopped');
            }, 500);
        }
    };

    const receiveHandler = client.receive("1", onMessage, onError, { eventPosition: EventPosition.fromEnqueuedTime(new Date(0)) });
}

main().catch((err) => {
    console.fatal(`Unexpected error: ${err.message}`);
    console.fatal(err);
    process.exit(127);
});
```

**Expected behaviour**

When `.stop()` is called the receiver should actually stop.

**Package-name:** azure-event-hubs

**Package-version:** 0.2.3

**node.js version:** v8.11.3

OS name and version: macOs High Sierra 10.13.6

**Additional context**

The event hub that I am pulling from has lots and lots of small messages on it and I am calling the `.stop` on the receiveHandler while it is working.

**Comment by amarzavery** [comment] 2018-07-25 04:14
version 0.2.5 has lot of changes from version 0.2.3. I would recommend running this script against the github branch that you have pulled down rather than using a published npm version.

**Comment by amarzavery** [comment] 2018-07-25 04:17
One more thing can you set the environment variable DEBUG to the following value and then run the script
```bash
export DEBUG=azure*,rhea*,-rhea:raw,-rhea:message,-azure:amqp-common:datatransformer
```

Please provide the debug logs. That will help us find the root cause. Please make sure to run against the source code checked in the master branch.

**Comment by Bruce-at-Buddy** [comment] 2018-07-25 04:29
BTW, this is the code I am using to flood the hub with messages

```javascript
const { EventHubClient } = require('azure-event-hubs');
const Chance = require('chance');

async function main() {

    const client = await EventHubClient.createFromConnectionString(
        process.env["EVENTHUB_CONNECTION_STRING"],
        process.env["EVENTHUB_NAME"]
    );

    console.info('Client created');

    const chance = new Chance();
    setInterval(async () => {

        const eventData = { body: `Hello ${chance.name()}` };
        await client.send(eventData);
        console.info(`Message sent successfully: ${JSON.stringify(eventData)}`);
    }, 500);
}

main().catch((err) => {
    console.fatal(`Unexpected error: ${err.message}`);
    console.fatal(err);
    process.exit(127);
});
```

**Comment by Bruce-at-Buddy** [comment] 2018-07-25 04:32
By the way, I was using `0.2.5` and seeing the same issue but found #113 which is why I reported it against `0.2.3` as it was at least reporting the correct error message.

**Comment by amarzavery** [comment] 2018-07-25 04:46
Is it possible to email me the connectionstring for your EventHub at amzavery@microsoft.com. You can invalidate the tokens after few hours. This can help me in reproducing the problem and I can probably find the root cause.

**Closed** 2018-07-31 19:53 UTC
Labels: Planned-Sprint-122, to do
