### ISSUE TITLE
No data was received from 'N' partitions

### ISSUE THREAD

**Issue by yanisIk** [Azure/azure-event-hubs-node#75] opened 2018-05-25 16:54 UTC
Hi,

I have two eventhubs having 8 partitions each.

My partition key is `"ticker"` and the data looks like: `{ticker: "MSFT", price: 100}`
I'm tracking and sending 17 different tickers, which means 17 different `PartitionKey` values.

When sampling (with different time ranges, from 1mn to 10mn), it says that No event was received from N Partitions (changes everytime I sample), and when I lookup the data, there are less keys than 17 (I double checked from the producer and the producer is sending all keys)

How can I debug this ? Since EventHubs hashes the PartitionKey to send the event to a specific Partition, what is happening in this case ? (17 different keys, 8 Partitions, N empty partitions)

Thanks.

**Comment by amarzavery** [comment] 2018-05-25 18:42
> My partition key is "ticker" and the data looks like: {ticker: "MSFT", price: 100}.
Do you mean the partition key is value of the ticker property from the data i.e "MSFT" or some other value?

If you send the data `await client.send({body: {ticker: "MSFT", price: 100}, partitionKey: "ticker"});`, then all the messages will always go to one partition since EH should hash the value "ticker" and come up with a same partition id all the time. If the paritionKey is the ticker symbol like "MSFT", "AMZN", "NFLX", etc. then EH will hash those values and send them to a specific partitionId. The partitionIds may be different.  It could be possible that the hashing algorithm would translate "MSFT" and "NFLX" to the same partition with id "1".

> When sampling (with different time ranges, from 1mn to 10mn), it says that No event was received from N Partitions (changes everytime I sample), and when I lookup the data, there are less keys than 17 (I double checked from the producer and the producer is sending all keys)

What kind of EventPosition are you specifying while receiving events from the partition. If you specify a time that is later than the time at which the events were sent then you would not receive those events. 

**Can you share the snippet of send and receive?**

How can I debug this ? Since EventHubs hashes the PartitionKey to send the event to a specific Partition, what is happening in this case ? (17 different keys, 8 Partitions, N empty partitions)

`export DEBUG=azure*,rhea*` should show the debug logs.


If you want to actually debug your application then you can use [vscode](https://code.visualstudio.com/) as the IDE. It provides excellent debugging functionality. You can debug your application by having a config like [this](https://github.com/Azure/azure-event-hubs-node/blob/master/.vscode/launch.json#L43-L52) in the `.vscode/launch.json` file.

**Comment by yanisIk** [comment] 2018-05-25 19:28
Hi @amarzavery,

I'm sending the event correcly as such: `ticksEventHubClient.send({body: tick, partitionKey: tick.ticker});`

The partitioning seems to be done correctly, I verified if each existing key goes to the same partition and it does, which is fine.

Now the issue is on the other side when it comes out of the eventhub.
I do it using the sample feature and I always chose a time range in the past where I know my program has been pushing data.

Nothing seems wrong on the application side. I logged every event going out correctly and can see that all data is sent correctly.

Will check what I can see with the DEBUG mode

**Comment by amarzavery** [comment] 2018-05-25 21:15
> The partitioning seems to be done correctly, I verified if each existing key goes to the same partition and it does, which is fine.

How did you verify this? I believe the only way to verify this is to receive messages from the eventhub and make sure that messages with different partition keys did not come from the same partition. If you can do this, it means you can receive messages from the EventHub (i.e messages coming out of the Event hub).

> Now the issue is on the other side when it comes out of the eventhub.
I do it using the sample feature and I always chose a time range in the past where I know my program has been pushing data.

Can you elaborate more about the sample feature? I am not clear what do you mean by this. A code snippet of what you are doing would be really helpful for me to able to help you.

**Comment by yanisIk** [comment] 2018-05-25 23:15
I'm using Stream Analytics with EventHub, and when you select EventHub as an input, you can download a sample from it just by clicking on a button and that is how I can verify what's coming out from EventHub.


And that is also how I know that some partitions were empty, the Azure UI tells me if a partition didn't send anything when downloading the sample.


I will continue to test this and see if it's not coming from my app. The partitioning is done correctly so that's already good.

I will let you know if I find something.

Thanks.

**Comment by amarzavery** [comment] 2018-05-25 23:30
There was a similar [issue](https://github.com/Azure/azure-event-hubs-node/issues/60) filed by another customer. I was able to reproduce that and also provided a fix for the same.

If there is an error in the response, at times the portal says it did not receive anything rather than surfacing the error. Hence, I would recommend opening up the debugger console (debugger tools) of the browser, look at the networking tab and check the response.

Apart from that, I would also recommend writing a simple receiver using the event hubs node.js sdk and verify whether you are able to receive the messages. That would confirm that the sdk works correctly independently and there are issues in running it with StreamAnalytics.

**Comment by yanisIk** [comment] 2018-05-30 21:34
Hi @amarzavery , the issue was intermitent and hard to debug, plus I had other issues with stream analytics where I didn't have error messages and cryptic behavior from ASA (spent almost 1 complete month doing trials and errors).

I decided to stop using ASA and moved to AWS Kinesis Analytics where I managed to migrate my whole project from ASA to Kinesis in one day and it ended working directly.

What made me switch is mostly ASA, this library is ok and does the job, thanks for maintaining it.

**My last feedback to help you improve this:**

- Create a Node Stream interface (the Kinesis libraries do that and it works like a charm, automatic backpressure management, batch management and more).

- The way this library is sending the messages is synchronous, if we wait for the message to send before sending the next one (`await client.send`), we can only send  one by one. If we don't wait, we risk to create too many eventlisteners. To send N events concurently, I had to use a queue with N concurrent limit.

**Comment by amarzavery** [comment] 2018-05-30 22:40
I am sorry to hear about the bad experience with Stream Analytics service. I would provide this feedback to the Stream Analytics folks. 

Thank you for the feedback for this library. We have plans to optimize the sender and will be doing that shortly. As you can see that the library was rewritten from scratch and is currently in preview. We will definitely improve this experience. I have filed an issue for this https://github.com/Azure/azure-event-hubs-node/issues/76.

**Comment by amarzavery** [comment] 2018-05-31 07:00
Hi @yanisIk - I have informed the ASA service team about your experience. They would like to have a direct conversation with you. Your feedback is valuable to us and we can definitely improve the customer experience. Can you please provide your email address or email me at amzavery@microsoft.com? I shall forward this to the ASA team so they can get in touch with you. Once again sorry for the sub par experience. I am sure Microsoft can do better with your feedback :).

**Comment by ramya-rao-a** [comment] 2019-01-15 22:51
Closing this issue as we plan to track the rest of the work in #76 like @amarzavery has mentioned above

**Closed by ramya-rao-a** 2019-01-15 22:51 UTC
Labels: Client, Event Hub
