### ISSUE TITLE
Client crashing with Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by MatejSkrbis** [Azure/azure-event-hubs-node#171] opened 2018-10-30 15:04 UTC
After running for some time, the application randomly crashes with error:

TypeError: Cannot read property 'options' of undefined
    at Object.translate (...\node_modules\rhea-promise\lib\eventContext.ts:97:49)
    at emit (...\node_modules\rhea-promise\lib\util\utils.ts:184:20)
    at Object.emitEvent (...\node_modules\rhea-promise\lib\util\utils.ts:195:5)
    at Connection._connection.on (...\node_modules\rhea-promise\lib\connection.ts:506:10)
    at emitOne (events.js:116:13)
    at Connection.emit (events.js:211:7)
    at Connection.dispatch (...\node_modules\rhea\lib\connection.js:229:37)
    at Connection.input (...\node_modules\rhea\lib\connection.js:502:18)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)

It seems as 'protocol_error' (eventName = 'protocolError') event is emitted and received at https://github.com/amqp/rhea-promise/blob/master/lib/connection.ts#L498 
context is then set to:
{
  message:"attach received on invalid channel 2"
  name:"ProtocolError"
}

It seems it's much easier to reproduce this issue under high load when reading or writing from many partitions. With low load it can take days or more to get this error.

Package version:
"@azure/event-hubs": "1.0.7"

**Comment by amarzavery** [comment] 2018-10-30 17:36
So I have fixed the options of undefined error in the latest version of rhea-promise (0.1.9). Source code change in the repo is over [here](https://github.com/amqp/rhea-promise/blob/master/lib/eventContext.ts#L97).

What worries me is this error
```
message:"attach received on invalid channel 2"
name:"ProtocolError"
```
It seems the sdk is trying to attach to an already closed session. Can you provide me some error logs
by setting the DEBUG variable to: 
```
export DEBUG=azure:event-hubs:error,azure-amqp-common:error,rhea-promise:error,rhea:events,rhea:frames,rhea:io,rhea:flow
```

That will provide me some context on the sequence of events that happened before this error occurred.

**Comment by amarzavery** [comment] 2018-11-07 00:02
@MatejSkrbis - That is some useful information. Looks like sdk received some messages after the receiver link was detached. Hence we see this error. 
Are you using the basic event hubs client or are you using the event processor host?
Will try to reproduce this error.
@grs - Any idea what can cause the `transfer after detach` error as mentioned above?

**Comment by grs** [comment] 2018-11-07 00:20
@amarzavery it is raised when a transfer is received on a link that the peer already issued a detach for

**Comment by MatejSkrbis** [comment] 2018-11-07 07:09
@amarzavery I am using event hubs client. Event processor host was less stable and was crashing much more often so I switched back to event hub clients.

**Comment by grs** [comment] 2018-11-07 09:18
@amarzavery yes, that is what it *looks* like

**Comment by ramya-rao-a** [comment] 2019-02-09 04:20
@MatejSkrbis Have you see this "transfer after detach" error ever since? Since it was concluded that we might need to loop in the service team here, it would help if we know if this has happened again

**Comment by MatejSkrbis** [comment] 2019-02-09 08:35
I don't remember getting this error since I updated to "@azure/event-hubs": "1.0.8". I'm not sure if it was a rhea thing or not, but I am not getting this anymore.

**Comment by ramya-rao-a** [comment] 2019-02-09 20:57
Thanks @MatejSkrbis 
I'll close this issue for now then.

If you see this error ("transfer after detach") again, please do log an issue.

**Closed by ramya-rao-a** 2019-02-09 20:57 UTC
Labels: Client, Event Hub, bug
